version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: always
    environment:
      - TZ=GB
    network_mode: host
    volumes:
      - /opt/docker-plex/config:/config
      - /opt/docker-plex/transcode:/transcode
      - /mnt:/data
